services:
  db:
    container_name: db
    image: bitnami/postgresql:16.3.0
    platform: linux/amd64
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=spring
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U docker"]
        interval: 5s
        timeout: 3s
        retries: 5
    networks:
      - docker-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - docker-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - docker-network
 
volumes:
  db-data:

networks:
  docker-network:
    driver: bridge
